trigger:
  branches:
    include:
    - main

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: BuildJob
        displayName: Build job
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - script: |
            echo Building the application...
          displayName: 'Build'
        - script: |
            echo Running unit tests...
          displayName: 'Unit tests'

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeployWeb
        displayName: Deploy web job
        pool:
          vmImage: 'ubuntu-latest'
        environment:
          name: 'production'
          resourceType: 'VirtualMachine'
        strategy:
          runOnce:
            deploy:
              steps:
              - script: |
                  echo Deploying the application...
                displayName: 'Deploy'
